Load the dataset (https://www.kaggle.com/chandramoulinaidu/spam-classification-for-basic-nlp)


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Spam Email raw text for NLP.csv')
# 1 spam
# 0 not spam

In [ ]:
df.head()

CATEGORY                                            MESSAGE  \
0         1  Dear Homeowner,\n\n \n\nInterest Rates are at ...   
1         1  ATTENTION: This is a MUST for ALL Computer Use...   
2         1  This is a multi-part message in MIME format.\n...   
3         1  IMPORTANT INFORMATION:\n\n\n\nThe new domain n...   
4         1  This is the bottom line.  If you can GIVE AWAY...   

                                FILE_NAME  
0  00249.5f45607c1bffe89f60ba1ec9f878039a  
1  00373.ebe8670ac56b04125c25100a36ab0510  
2  00214.1367039e50dc6b7adb0f2aa8aba83216  
3  00210.050ffd105bd4e006771ee63cabc59978  
4  00033.9babb58d9298daa2963d4f514193d7d6

In [ ]:
df.tail()

CATEGORY                                            MESSAGE  \
5791         0  I'm one of the 30,000 but it's not working ver...   
5792         0  Damien Morton quoted:\n\n>W3C approves HTML 4 ...   
5793         0  On Mon, 2002-07-22 at 06:50, che wrote:\n\n\n\...   
5794         0  Once upon a time, Manfred wrote :\n\n\n\n> I w...   
5795         0  If you run Pick, and then use the "New FTOC" b...   

                                   FILE_NAME  
5791  00609.dd49926ce94a1ea328cce9b62825bc97  
5792  00957.e0b56b117f3ec5f85e432a9d2a47801f  
5793  01127.841233b48eceb74a825417d8d918abf8  
5794  01178.5c977dff972cd6eef64d4173b90307f0  
5795  00747.352d424267d36975a7b40b85ffd0885e

In [ ]:
df['CATEGORY'].value_counts()

CATEGORY
0    3900
1    1896
Name: count, dtype: int64

In [ ]:
import nltk

nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
tokenizer = nltk.RegexpTokenizer(r"\w+")
test_message = "Hey,, GGggGG feet it going? <HTML><bads> bads 'randoms' badly"

test_message_tokenized = tokenizer.tokenize(test_message)
test_message_tokenized

['Hey',
 'GGggGG',
 'feet',
 'it',
 'going',
 'HTML',
 'bads',
 'bads',
 'randoms',
 'badly']

In [ ]:
test_message_lowercased = [t.lower() for t in test_message_tokenized]
test_message_lowercased

['hey',
 'gggggg',
 'feet',
 'it',
 'going',
 'html',
 'bads',
 'bads',
 'randoms',
 'badly']

In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

test_message_lemmatized_tokens = [lemmatizer.lemmatize(t) for t in test_message_lowercased]
test_message_lemmatized_tokens

['hey',
 'gggggg',
 'foot',
 'it',
 'going',
 'html',
 'bad',
 'bad',
 'randoms',
 'badly']

In [ ]:
from nltk.corpus import stopwords

stopwords = stopwords.words('english')

test_message_useful_tokens = [t for t in test_message_lemmatized_tokens if t not in stopwords]
test_message_useful_tokens

['hey', 'gggggg', 'foot', 'going', 'html', 'bad', 'bad', 'randoms', 'badly']

In [ ]:
def message_to_token_list(s):
  tokens = tokenizer.tokenize(s)
  lowercased_tokens = [t.lower() for t in tokens]
  lemmatized_tokens = [lemmatizer.lemmatize(t) for t in lowercased_tokens]
  useful_tokens = [t for t in lemmatized_tokens if t not in stopwords]

  return useful_tokens

message_to_token_list(test_message)

['hey', 'gggggg', 'foot', 'going', 'html', 'bad', 'bad', 'randoms', 'badly']

In [ ]:
df = df.sample(frac=1, random_state=1)
df = df.reset_index(drop=True)

split_index = int(len(df) * 0.8)
train_df, test_df = df[:split_index], df[split_index:]

train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

train_df, test_df

(      CATEGORY                                            MESSAGE  \
 0            1  <HTML>\n\n<BODY>\n\n<META HTTP-EQUIV=3D"Conten...   
 1            1  <html>\n\n\n\n\n\n</head>\n\n\n\n<body>\n\n\n\...   
 2            1  <HTML><HEAD><TITLE>New Web Technology</TITLE>\...   
 3            1  \n\n<HTML>\n\n<HEAD>\n\n<TITLE>bizmagoffer</TI...   
 4            0  URL: http://boingboing.net/#85485824\n\nDate: ...   
 ...        ...                                                ...   
 4631         0  Doom 3 will be based on a peer to peer archite...   
 4632         1  \n\n\n\n<HTML>\n\n<HEAD>\n\n<TITLE>Cards In Ad...   
 4633         1  <BODY BGCOLOR="#FFFFFF">\n\n\n\n<DIV ALIGN="ce...   
 4634         0  Yes - great minds think alike. But even withpu...   
 4635         0  On Tue, Aug 06, 2002 at 04:21:22 +0100, David ...   
 
                                    FILE_NAME  
 0     00275.87c74dc27e397ccd3b2b581bbefef515  
 1     00531.f3fffa4504c7009a03dd0d44a4562a84  
 2     01078.5

In [ ]:
token_counter = {}

for message in train_df['MESSAGE']:
  message_as_token_lst = message_to_token_list(message)

  for token in message_as_token_lst:
    if token in token_counter:
      token_counter[token] += 1
    else:
      token_counter[token] = 1

len(token_counter)

76940

In [ ]:
token_counter

{'html': 4277,
 'body': 1944,
 'meta': 758,
 'http': 15589,
 'equiv': 448,
 '3d': 34353,
 'content': 2864,
 'type': 2830,
 'text': 2638,
 'charset': 904,
 '3diso': 123,
 '8859': 486,
 '1': 8516,
 'doctype': 115,
 'public': 551,
 'w3c': 123,
 'dtd': 123,
 '4': 3169,
 '0': 9313,
 'transitional': 117,
 'en': 571,
 'head': 1325,
 '3dcontent': 71,
 'mshtml': 85,
 '5': 2989,
 '50': 1643,
 '4134': 19,
 '600': 220,
 'name': 3455,
 '3dgenerator': 67,
 'style': 3307,
 'bgcolor': 2866,
 'ffffff': 2465,
 'div': 3119,
 'nbsp': 10203,
 'font': 34416,
 'size': 13242,
 '3d2': 1043,
 'p': 10622,
 'align': 6914,
 '3dcenter': 715,
 'face': 9616,
 'time': 3142,
 'new': 2651,
 'roman': 498,
 '3d5': 168,
 'em': 433,
 'chickw': 1,
 'eed': 3,
 'healing': 10,
 'salve': 9,
 '3d3': 430,
 'natural': 216,
 'way': 1323,
 'healthy': 37,
 'skin': 54,
 'br': 15303,
 'h': 525,
 'ealing': 1,
 'problem': 961,
 'psoriasis': 1,
 'cancer': 57,
 'rash': 5,
 'sore': 7,
 'throat': 19,
 'di': 30,
 'v': 411,
 'cut': 129,
 'nb': 

In [ ]:
def keep_token(proccessed_token, threshold):
  if proccessed_token not in token_counter:
    return False
  else:
    return token_counter[proccessed_token] > threshold

keep_token('random', 100)

False

In [ ]:
features = set()

for token in token_counter:
  if keep_token(token, 10000):
    features.add(token)

features

{'3d', 'b', 'br', 'com', 'font', 'http', 'nbsp', 'p', 'size', 'td', 'tr'}

In [ ]:
features = list(features)
features

['3d', 'p', 'b', 'http', 'com', 'tr', 'br', 'td', 'font', 'size', 'nbsp']

In [ ]:
token_to_index_mapping = {t:i for t, i in zip(features, range(len(features)))}
token_to_index_mapping

{'3d': 0,
 'p': 1,
 'b': 2,
 'http': 3,
 'com': 4,
 'tr': 5,
 'br': 6,
 'td': 7,
 'font': 8,
 'size': 9,
 'nbsp': 10}

In [ ]:
message_to_token_list('3d b <br> .com bad font font com randoms')

['3d', 'b', 'br', 'com', 'bad', 'font', 'font', 'com', 'randoms']

In [ ]:
# "Bag of Words" (counts vector)

# ->  http  tr  size  3d  font  br  com  td   p   b
# ->    0    1    2    3   4    5    6    7   8   9
# ->   [0,   0,   0,   1,  2,   1,   2,   0,  0,  1]

[0.,  0.,  0.,   1., 2.,  1., 2.,  0., 0., 1.]

[0.0, 0.0, 0.0, 1.0, 2.0, 1.0, 2.0, 0.0, 0.0, 1.0]

In [ ]:
import numpy as np

def message_to_count_vector(message):
  count_vector = np.zeros(len(features))

  processed_list_of_tokens = message_to_token_list(message)

  for token in processed_list_of_tokens:
    if token not in features:
      continue
    index = token_to_index_mapping[token]
    count_vector[index] += 1

  return count_vector

message_to_count_vector('3d b <br> .com bad font font com randoms')

array([1., 0., 1., 0., 2., 0., 1., 0., 2., 0., 0.])

In [ ]:
message_to_count_vector(train_df['MESSAGE'].iloc[3])

array([ 0.,  7., 14., 13., 15., 32.,  7., 36., 30., 12.,  7.])

In [ ]:
train_df.iloc[3]

CATEGORY                                                     1
MESSAGE      \n\n<HTML>\n\n<HEAD>\n\n<TITLE>bizmagoffer</TI...
FILE_NAME               00627.4e9619c454da17a27d4a66c87583dd49
Name: 3, dtype: object

In [ ]:
def df_to_X_y(dff):
  y = dff['CATEGORY'].to_numpy().astype(int)

  message_col = dff['MESSAGE']
  count_vectors = []

  for message in message_col:
    count_vector = message_to_count_vector(message)
    count_vectors.append(count_vector)

  X = np.array(count_vectors).astype(int)

  return X, y

In [ ]:
X_train, y_train = df_to_X_y(train_df)

X_test, y_test = df_to_X_y(test_df)

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4636, 11), (4636,), (1160, 11), (1160,))

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().fit(X_train)

X_train, X_test = scaler.transform(X_train), scaler.transform(X_test)

X_train

array([[0.01559454, 0.02439024, 0.2254902 , ..., 0.02089736, 0.03579418,
        0.08818342],
       [0.21052632, 0.1097561 , 0.31372549, ..., 0.05285802, 0.05592841,
        0.01587302],
       [0.11111111, 0.04065041, 0.2745098 , ..., 0.02950215, 0.05592841,
        0.        ],
       ...,
       [0.        , 0.00406504, 0.        , ..., 0.00614628, 0.01118568,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

lr = LogisticRegression().fit(X_train, y_train)
print(classification_report(y_test, lr.predict(X_test)))


              precision    recall  f1-score   support

           0       0.77      1.00      0.87       790
           1       0.99      0.35      0.52       370

    accuracy                           0.79      1160
   macro avg       0.88      0.68      0.69      1160
weighted avg       0.84      0.79      0.76      1160



In [ ]:
# Compare logistic regression to random forest

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier().fit(X_train, y_train)
print(classification_report(y_test, rf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89       790
           1       0.87      0.59      0.70       370

    accuracy                           0.84      1160
   macro avg       0.85      0.77      0.80      1160
weighted avg       0.84      0.84      0.83      1160

